resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

description 'ESX Supermarket'

version '1.0.1'

files {
	'html/ui.html',
	'html/styles.css',
	'html/scripts.js',
	'html/debounce.min.js',
	'html/iransans.otf',
	
	'html/img/bag.png',
	'html/img/bread.png',
	'html/img/grand_cru.png',
	'html/img/raisin.png',
	'html/img/vine.png',
	'html/img/jus_raisin.png',
	'html/img/fixkit.png',
	'html/img/soda.png',
	'html/img/banana.png',
	'html/img/orange.png',
	'html/img/donut.png',
	'html/img/energy.png',
	'html/img/jusfruit.png',
	'html/img/close.png',
	'html/img/croquettes.png',
	'html/img/water.png',
	'html/img/plus.png',
	'html/img/minus.png',	
	'html/img/bandage.png',
    'html/img/beer.png',
    'html/img/binoculars.png',
    'html/img/cannabis.png',
    'html/img/cigarette.png',
    'html/img/clip.png',
    'html/img/cocacola.png',
    'html/img/coffee.png',
    'html/img/coke.png',
    'html/img/gold.png',
    'html/img/hamburger.png',
    'html/img/cash.png',
    'html/img/chocolate.png',
    'html/img/iron.png',
    'html/img/jewels.png',
    'html/img/medikit.png',
    'html/img/tequila.png',
    'html/img/whisky.png',
    'html/img/limonade.png',
    'html/img/phone.png',
    'html/img/vodka.png',
    'html/img/cupcake.png',
    'html/img/drpepper.png',
    'html/img/energy.png',
    'html/img/croquettes.png',
    'html/img/bolpistache.png',
    'html/img/bolnoixcajou.png',
    'html/img/bolcacahuetes.png',
    'html/img/bolchips.png',
    'html/img/black_money.png',
    'html/img/WEAPON_APPISTOL.png',
    'html/img/WEAPON_ASSAULTRIFLE.png',
    'html/img/WEAPON_ASSAULTSHOTGUN.png',
    'html/img/WEAPON_BOTTLE.png',
    'html/img/WEAPON_BULLPUPRIFLE.png',
    'html/img/WEAPON_CARBINERIFLE.png',
    'html/img/WEAPON_COMBATMG.png',
    'html/img/WEAPON_BAT.png',
    'html/img/WEAPON_COMBATPISTOL.png',
    'html/img/WEAPON_CROWBAR.png',
    'html/img/WEAPON_GOLFCLUB.png',
    'html/img/WEAPON_KNIFE.png',
    'html/img/WEAPON_MICROSMG.png',
    'html/img/WEAPON_NIGHTSTICK.png',
    'html/img/WEAPON_HAMMER.png',
    'html/img/WEAPON_PISTOL.png',
    'html/img/WEAPON_PUMPSHOTGUN.png',
    'html/img/WEAPON_SAWNOFFSHOTGUN.png',
    'html/img/WEAPON_SMG.png',
    'html/img/WEAPON_STUNGUN.png',
    'html/img/WEAPON_SPECIALCARBINE.png',
    'html/img/WEAPON_KNUCKLE.png',
    'html/img/WEAPON_FLASHLIGHT.png',
    'html/img/WEAPON_REVOLVER.png',
    'html/img/WEAPON_DAGGER.png',
    'html/img/WEAPON_PETROLCAN.png',
    'html/img/WEAPON_PISTOL50.png',
    'html/img/WEAPON_DBSHOTGUN.png',
    'html/img/WEAPON_SWITCHBLADE.png',
    'html/img/WEAPON_POOLCUE.png'
}

ui_page 'html/ui.html'

client_scripts {
	'@es_extended/locale.lua',
	'locales/de.lua',
	'locales/br.lua',
	'locales/en.lua',
	'locales/fi.lua',
	'locales/fr.lua',
	'locales/es.lua',
	'locales/sv.lua',
	'locales/pl.lua',
	'locales/fa.lua',
	'config.lua',
	'client/main.lua'
}

server_scripts {
	'@es_extended/locale.lua',
	'@mysql-async/lib/MySQL.lua',
	'locales/de.lua',
	'locales/br.lua',
	'locales/en.lua',
	'locales/fi.lua',
	'locales/fr.lua',
	'locales/es.lua',
	'locales/sv.lua',
	'locales/pl.lua',
	'locales/fa.lua',
	'config.lua',
	'server/main.lua'
}

dependency 'es_extended'
