Config = {}

Config.Animations = {

	{
		name  = 'festlich',
		label = 'Festlich',
		items = {
			{label = "Eine Zigarette rauchen", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING", flag = 9}},
			{label = "Musik spielen", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN", flag = 9}},
			{label = "Dj", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj", flag = 9}},
			{label = "Ein Bier Trinken", type = "scenario", data = {anim = "WORLD_HUMAN_DRINKING", flag = 9}},
			{label = "Bier zur Musik", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING", flag = 9}},
			{label = "Luftgitarre", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar", flag = 9}},
			{label = "Luftbewegung", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging", flag = 9}},
			{label = "Rock'n'roll", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock", flag = 9}},
			-- {label = "Fumer un joint", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING_POT", flag = 9}},
			{label = "Auf der stelle", type = "anim", data = {lib = "amb@world_human_bum_standing@drunk@idle_a", anim = "idle_a", flag = 9}},
			{label = "Erbrechen im Auto", type = "anim", data = {lib = "oddjobs@taxi@tie", anim = "vomit_outside", flag = 9}},
			
		}
	},

	{
		name  = 'grussformen',
		label = 'Grussform',
		items = {
			{label = "Gruß", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello", flag = 9}},
			{label = "Hand schütteln", type = "anim", data = {lib = "mp_common", anim = "givetake1_a", flag = 9}},
			{label = "moin", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a", flag = 9}},
			{label = "Hallo Gangster", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a", flag = 9}},
			{label = "Militärgruß", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute", flag = 9}},
		}
	},

	{
		name  = 'arbeit',
		label = 'Arbeit',
		items = {
			{label = "Verdächtiger: geh zur Polizei", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_c", flag = 9}},
			{label = "Fischer", type = "scenario", data = {anim = "world_human_stand_fishing", flag = 9}},
			{label = "Polizei: untersuchen", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f", flag = 9}},
			{label = "Polizei: im Funk sprechen", type = "anim", data = {lib = "random@arrests", anim = "generic_radio_chatter", flag = 9}},
			{label = "Polizei: Verkehr", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT", flag = 9}},
			{label = "Polizei: Fernglas", type = "scenario", data = {anim = "WORLD_HUMAN_BINOCULARS", flag = 9}},
			{label = "Landwirtschaft: Ernte", type = "scenario", data = {anim = "world_human_gardener_plant", flag = 9}},
			{label = "ACLS: Repariere den Motor", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped", flag = 9}},
			{label = "Arzt: beobachten", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL", flag = 9}},
			{label = "Taxi: Mit dem Kunden Sprechen", type = "anim", data = {lib = "oddjobs@taxi@driver", anim = "leanover_idle", flag = 9}},
			{label = "Taxi: Geben Sie die Rechnung", type = "anim", data = {lib = "oddjobs@taxi@cyi", anim = "std_hand_off_ps_passenger", flag = 9}},
			{label = "Lebensmittelhändler: Den Einkauf geben", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper", flag = 9}},
			{label = "Barkeeper: Einen Schuss servieren", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b", flag = 9}},
			{label = "Reporter: Ein Foto Machen", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI", flag = 9}},
			{label = "Alle Beruf: Sich eine Notizen Machen", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD", flag = 9}},
			{label = "Alle Berufe: Hammerschlag", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING", flag = 9}},
			{label = "Penner : Die runde Machen", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY", flag = 9}},
			{label = "Penner : Dastehen wie eine Statur", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE", flag = 9}},
		}
	},

	{
		name  = 'humor',
		label = 'Humor',
		items = {
			{label = "Gratulieren", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING", flag = 9}},
			{label = "Groß", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06", flag = 9}},
			{label = "Sie", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point", flag = 9}},
			{label = "Kommen", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft", flag = 9}}, 
			{label = "Keskya ?", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on", flag = 9}},
			{label = "Für mich", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_me", flag = 9}},
			{label = "Ich hab's gewusst.", type = "anim", data = {lib = "anim@am_hold_up@male", anim = "shoplift_high", flag = 9}},
			{label = "Ich wusste es, verdammt.", type = "scenario", data = {lib = "amb@world_human_jog_standing@male@idle_b", anim = "idle_d", flag = 9}},
			{label = "Ich sitz in der Klemme", type = "scenario", data = {lib = "amb@world_human_bum_standing@depressed@idle_a", anim = "idle_a", flag = 9}},
			{label = "Facepalm", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm", flag = 9}},
			{label = "Ganz ruhig!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now", flag = 9}},
			{label = "Was habe ich getan?", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a", flag = 9}},
			{label = "Fürchten", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right", flag = 9}},
			{label = "Kämpfen?", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e", flag = 9}},
			{label = "Das kann nicht sein!", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn", flag = 9}},
			{label = "Umarmen", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a", flag = 9}},
			{label = "Finger zeigen", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter", flag = 9}},
			{label = "Du Clown", type = "anim", data = {lib = "mp_player_int_upperwank", anim = "mp_player_int_wank_01", flag = 9}},
			{label = "Eine Kugel in den Kopf", type = "anim", data = {lib = "mp_suicide", anim = "pistol", flag = 9}},
		}
	},

	{
		name  = 'sport',
		label = 'Sport',
		items = {
			{label = "Muskeln spielen lassen", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base", flag = 9}},
			{label = "Gewichtsstange", type = "anim", data = {lib = "amb@world_human_muscle_free_weights@male@barbell@base", anim = "base", flag = 9}},
			{label = "Pumpen", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base", flag = 9}},
			{label = "Rumpfbeugen", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base", flag = 9}},
			{label = "Yoga", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a", flag = 9}},
		}
	},

	{
		name  = 'verschiedenes',
		label = 'Verschiedenes',
		items = {
			{label = "Tot", type = "anim", data = {lib = "misslamar1dead_body", anim = "dead_idle", flag = 9}},
			{label = "Einen Kaffee Trinken", type = "anim", data = {lib = "amb@world_human_aa_coffee@idle_a", anim = "idle_a", flag = 9}},
			{label = "Sitzen", type = "anim", data = {lib = "anim@heists@prison_heistunfinished_biztarget_idle", anim = "target_idle", flag = 9}},
			{label = "Gegen die Mauer", type = "scenario", data = {anim = "world_human_leaning", flag = 9}},
			{label = "Auf dem Rücken liegen", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK", flag = 9}},
			{label = "Auf dem Bauch liegen", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE", flag = 9}},
			{label = "Etwas säubern", type = "scenario", data = {anim = "world_human_maid_clean", flag = 9}},
			{label = "Etwas zu Essen machen", type = "scenario", data = {anim = "PROP_HUMAN_BBQ", flag = 9}},
			{label = "Durschstöbern", type = "anim", data = {lib = "mini@prostitutes@sexlow_veh", anim = "low_car_bj_to_prop_female", flag = 9}},
			{label = "Ein selfie machen", type = "scenario", data = {anim = "world_human_tourist_mobile", flag = 9}},
			{label = "Lauschen", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base", flag = 9}}, 
		}
	},

	{
		name  = 'haltung',
		label = 'Haltung',
		items = {
			{label = "Verwundet", type = "attitude", data = {lib = "move_m@injured", anim = "move_m@injured", flag = 9}},
			{label = "Normal M", type = "attitude", data = {lib = "move_m@confident", anim = "move_m@confident", flag = 9}},
			{label = "Normal F", type = "attitude", data = {lib = "move_f@heels@c", anim = "move_f@heels@c", flag = 9}},
			{label = "Depressiv", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a", flag = 9}},
			{label = "Depressiv F", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a", flag = 9}},
			{label = "Geschäftlich", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a", flag = 9}},
			{label = "Bestimmend", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a", flag = 9}},
			{label = "Beiläufig", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a", flag = 9}},
			{label = "Zu viel gegessen", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a", flag = 9}},
			{label = "Hipster", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a", flag = 9}},
			{label = "Einschüchtern", type = "attitude", data = {lib = "move_m@hurry@a", anim = "move_m@hurry@a", flag = 9}},
			{label = "Landstreicher", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a", flag = 9}},
			{label = "Unglücklich", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a", flag = 9}},
			{label = "Muskelin", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a", flag = 9}},
			{label = "Schockiert", type = "attitude", data = {lib = "move_m@shocked@a", anim = "move_m@shocked@a", flag = 9}},
			{label = "Finster", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a", flag = 9}},
			{label = "Ermüden", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed", flag = 9}},
			{label = "Presse", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a", flag = 9}},
			{label = "Stolz", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money", flag = 9}},
			{label = "Kurzes Rennen", type = "attitude", data = {lib = "move_m@quick", anim = "move_m@quick", flag = 9}},
			{label = "Weichei", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater", flag = 9}},
			{label = "Frech", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy", flag = 9}},	
			{label = "Arrogant", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a", flag = 9}},
		}
	},{
		name  = 'tanzen',
		label = 'Tanzen',
		items = {
		        {label = "Tanzen 1", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", anim = "mi-hi_amb_club_10_v1_male^6", flag = 9}},
				{label = "Tanzen 2", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@ds@base", anim = "idle_a_fp", flag = 9}},
				{label = "Tanzen 3", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@rds@base", anim = "idle_b", flag = 9}},
				{label = "Tanzen 4", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@std@ds@base", anim = "idle_a", flag = 9}},
				{label = "Tanzen 5", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_male^6", flag = 9}},
				{label = "Tanzen 6", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@low_intesnsity", anim = "li_dance_facedj_09_v1_male^6", flag = 9}},
				{label = "Tanzen 7", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_09_v1_male^6", flag = 9}},
				{label = "Tanzen 8", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_low_intensity", anim = "trans_dance_facedj_li_to_hi_07_v1_male^6", flag = 9}},
				{label = "Tanzen 9", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_13_v2_male^6", flag = 9}},
				{label = "Tanzen 10", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups_transitions@from_hi_intensity", anim = "trans_dance_crowd_hi_to_li__07_v1_male^6", flag = 9}},
				{label = "Tanzen 11", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@hi_intensity", anim = "hi_dance_prop_13_v1_male^6", flag = 9}},
				{label = "Tanzen 12", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@from_med_intensity", anim = "trans_crowd_prop_mi_to_li_11_v1_male^6", flag = 9}},
				{label = "Tanzen 13", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_up", flag = 9}},
				{label = "Tanzen 14", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right_up", flag = 9}},
				{label = "Tanzen 15", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@low_intensity", anim = "li_dance_crowd_17_v1_male^6", flag = 9}},
				{label = "Tanzen 16", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_med_intensity", anim = "trans_dance_facedj_mi_to_li_09_v1_male^6", flag = 9}},
				{label = "Tanzen 17", type = "anim", data = {lib = "special_ped@zombie@monologue_4@monologue_4l", anim = "iamtheundead_11", flag = 9}},
				{label = "Tanzen 18", type = "anim", data = {lib = "timetable@tracy@ig_5@idle_b", anim = "idle_e", flag = 9}},
				{label = "Tanzen 19", type = "anim", data = {lib = "mini@strip_club@idles@dj@idle_04", anim = "idle_04", flag = 9}},
				{label = "Tanzen 20", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_1@monologue_1a", anim = "mtn_dnc_if_you_want_to_get_to_heaven", flag = 9}},
				{label = "Tanzen 21", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_4@monologue_4a", anim = "mnt_dnc_verse", flag = 9}},
				{label = "Tanzen 22", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag", flag = 9}},
				{label = "Tanzen 23", type = "anim", data = {lib = "anim@amb@nightclub@dancers@black_madonna_entourage@", anim = "hi_dance_facedj_09_v2_male^5", flag = 9}},
				{label = "Tanzen 24", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_male^6", flag = 9}},
				{label = "Tanzen 25", type = "anim", data = {lib = "anim@amb@nightclub@dancers@dixon_entourage@", anim = "mi_dance_facedj_15_v1_male^4", flag = 9}},
				{label = "Tanzen 26", type = "anim", data = {lib = "anim@amb@nightclub@dancers@podium_dancers@", anim = "hi_dance_facedj_17_v2_male^5", flag = 9}},
				{label = "Tanzen 27", type = "anim", data = {lib = "anim@amb@nightclub@dancers@tale_of_us_entourage@", anim = "mi_dance_prop_13_v2_male^4", flag = 9}},
				{label = "Tanzen 28", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_cs", anim = "dance_loop_tao", flag = 9}},
				{label = "Tanzen 29", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao", flag = 9}},
				{label = "Tanzen 30", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@uncle_disco", anim = "uncle_disco", flag = 9}},
				{label = "Tanzen 31", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@raise_the_roof", anim = "raise_the_roof", flag = 9}},
				{label = "Tanzen 32", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@cats_cradle", anim = "cats_cradle", flag = 9}},
				{label = "Tanzen 33", type = "anim", data = {lib = "anim@mp_player_intupperbanging_tunes", anim = "idle_a", flag = 9}},
				{label = "Tanzen 34", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center", flag = 9}},
				{label = "Tanzen 35", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center", flag = 9}},
				{label = "Tanzen 36", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim = "high_center", flag = 9}},
				{label = "Tanzen 37", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@", anim = "trans_dance_facedj_hi_to_mi_11_v1_female^6", flag = 9}},
				{label = "Tanzen 38", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_07_v1_female^6", flag = 9}},
				{label = "Tanzen 39", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_female^6", flag = 9}},
				{label = "Tanzen 40", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_09_v1_female^6", flag = 9}},
				{label = "Tanzen 41", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_laz", flag = 9}},
		}
	},
}